# Site settings
title: Ohannes (Hovig) Ohannessian
twitter_username: hovig613
name: Ohannes (Hovig) Ohannessian

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.ibm.com/blogs/bluemix/author/oohanneus-ibm-com/
 - title: GitHub
   url: https://github.com/hovig
 - title: RPubs
   url: http://rpubs.com/hovig613
 - title: DWAnswers
   url: https://developer.ibm.com/answers/users/254251/hovig-ohannessian/
 - title: Stackoverflow
   url: https://stackoverflow.com/users/4360384/hovig
 - title: LinkedIn
   url: https://www.linkedin.com/in/hovig-ohannessian-55897231/
 - title: IBM Github
   url: https://github.ibm.com/oohanne
 - title: VisualCV
   url: https://www.visualcv.com/app/#/cvs/393640

#Any buzzword skills you want to include
skills:
 - Data Science
 - Internet of Things
 - Watson
 - Javascript
 - Python
 - Docker
 - Microservices
 - Java
 - NoSQL
 - SQL
 - REST
 - Kafka/Zookeeper
 - Visualization
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://twitter.com/hovig613

#Work experience is required
roles:
 - title: Software Engineer
   start: 2015
   end: Ongoing
   employer: IBM
   description: Designing and developing mobile, IoT and web applications (frontend/backend) including hands-on platform infrastructures using VM, Bluemix Cloud and SoftLayer. Worked as devops on server side development and configurations for Watson IoT Platform and others. Created prototypes and real world applications end-to-end (small and large scale). Working on different cloud projects including IBM’s Cloudprivate with Kubernetes. Participated to hackathons, code challenging tools online and created hackathon and workshops.
 - title: Software Engineer
   start: 2014
   end: 2015
   employer: Yerutech
   description: Solving problems to give people more discretionary time and reduce their stress level. Designing and developing mobile applications—available in the Android Play Store. Yerutech is a startup business for web apps, for Android and for Internet of Things.
- title: Software Engineer
   start: 2013
   end: 2014
   employer: innoWake
   description: Migration and application Modernization Company based in Germany. Worked as a junior Software Engineer dedicated to integrating software with third-party partners for the client.
 - title: Software Engineer
   start: 2011
   end: 2013
   employer: Gtech
   description: Leading gaming solutions company. Worked as a junior Software Engineer. Designed, developed, created Sales team demos, and maintained the baseline code.
 - title: Research Student Exchange
   start: 2010
   end: 2010
   employer: IBM – China Research Lab Team
   description: Worked with Data Visualization team. Researched about Machine Learning and Data Mining. Program funded by National Science Foundation (NSF) and LA PIRE. Selected based upon faculty recommendation.

#Education is required
education:
 - level: Masters of Science (MSDS online)
   date: 2019
   subject: Data Science
   school: CUNY
 - level: Bachelor of Science in Computer Engineering (BSCE)
   date: 2010
   subject: Computer Engineering
   school: Florida Atlantic University

#This section is optional (as is the image link below)
youtube:
   profileurl: https://www.youtube.com/channel/UCZIFTruEPSjQRmj7y48eAnA?view_as=subscriber
   videos:
    - title: Create, connect and simulate devices with Watson Data Platform and Node-Red
      link: https://www.youtube.com/watch?v=TufD9akAaXY&t=24s
      optionalimage: https://i.ytimg.com/vi/TufD9akAaXY/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAjsSfYTNsOxwOpYfAjRwU5_UGvkg
      date: Oct 12, 2017
    - title: Upload and analyze an image using Functions, Node-RED, Node.js & IoT Platform
      link: https://www.youtube.com/watch?v=WKnrbA-N13A
      optionalimage: https://i.ytimg.com/vi/WKnrbA-N13A/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBnypsq14agZmxYEWSOBqKyK9jNPw
      date: Oct 27, 2017
    - title: watson iot blockchain node-red
      link: https://www.youtube.com/watch?v=qI3a5QU0iys
      optionalimage: https://i.ytimg.com/vi/qI3a5QU0iys/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAxLZY3UKsZ7pdBzx2eN0AGPZBsrw
      date: Apr 16, 2018
    - title: pulse iot watson machine learning - web based mobile health app
      link: https://www.youtube.com/watch?v=mtzQQfU8VuU
      optionalimage: https://i.ytimg.com/vi/mtzQQfU8VuU/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLArXcXcYsqStnwlht86BaLs7oqyOw
      date: Apr 12, 2018

publications:
   profileurl: https://www.amazon.com/Arabica-Ohannes-Ohannessian/dp/1502585456/ref=sr_1_9?s=books&ie=UTF8&qid=1525749203&sr=1-9&keywords=arabica
   description: Wrote an instructional book to teach Arabic to English speaking audience using communicative sentences to make it easy conversing the language—selling on Amazon.
                •	ARABICA - Learn & Speak Arabic. Designed and wrote a practical, affordable book to make Arabic more accessible to English-speaking people.

member:
   profileurl: https://ieeexplore.ieee.org/
   organization: IEEE

#List of interesting Github repo/projects to include - optional
github:
 - hovig/pulse-iot-wml-mobile-health
 - hovig/kivoon
 - hovig/heart-beat-watson-machinelearning
 - hovig/rabbitmq-nodejs
 - hovig/Using-IOT-toProcess-BlockchainAnalytics
 - hovig/image-analysis-iot-alert
 - hovig/retail-pymongo-docker
 - hovig/dsxsquare
 - hovig/gyrolib
 - hovig/particle-android-bluemix
 - hovig/xbee-ethernet-arduino-nodered
 - hovig/gyro-watson-ml

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/4360384/hovig
   flairimageurl: https://stackoverflow.com/users/flair/4360384.png

#Mobile apps section is optional
apps:
 - name: Some of Android Apps
   platform: Android
   url: https://play.google.com/store/apps/developer?id=YeruTech&hl=en
   description: A basic early Android app (open sourced)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |

•	Bluemix: Node Red  and Push Notifications for Spark Core : Web and Mobile (Android) control of Particle Core device using Node-Red and Push notification on Bluemix to turn LED on/off through WiFi
•	Xbee, Ethernet, Arduino, Node Red and MongoDB: Project with Xbees, Arduinos, Ethernet and Bluemix. The data read from the device is saved in MongoDB database
•	Cognitive Builder Faire : Cognitive and Data innovation faire – Won the 2nd place in the data science hackathon
•	Simulate-iot app : A pattern creates a simulated motor and uses the Watson IoT Platform to monitor commands that you send to the motor
•	Analyze an image and send status alert : An  IoT app that uses Openwhisk serverless and Watson visual recognition to analyze images and send alert notifications
•	How to generate API key and token in IBM Watson IoT Platform
<strong>Technologies</strong>: android, node-red, java, xml, sqlite, bluemix, Watson apis, analytics, docker, apim, arduino, C, javascript, node.js, angularJS, devops, kafka/zookeeper, cloud, mqtt, security, react-redux, mongo, python (Codewars.com level: 4kyu), internet of things (connect devices to cloud from A to Z), AR, html, css, ajax, jquery, slack bot, devops, kubernetes, serverless, prometheus/alertmanager

•	CarLot - Park & Save: Designed to resolve ongoing inefficiency. Valuable to find a car in airport and mall parking lots. Save location to mobile device and use a route map to return to the saved location.  Calculates shortest walking route and estimated walking time. Includes  option to save a picture of the location to the file and many other options.
•	Attendance: Designed and coded app to resolve ongoing inefficiency. Applicable worldwide. Especially valuable to administrators needing to record attendance at  meetings, classes, and conferences. Replaces the need for hardcopy sign-in. Records attendee name, physical location at time of sign-in, date, and time.
•	Wisdom Of Solomon: Designed and coded to inspire people with great quotings and wisdoms. It has a great value of self-consciousness and a moment of thought for meditation.
•	Zruyts: Java based web application and Android app (both seperately) can communicate in one place (like chat room) can have multiple users joining in.
•	Bluemix Spark Core LED On/Off: Android app for a tutorial project to turn an LED on or off through HTTP request to a Particle Core WiFi device which in turns uses REST API to process that request.
•	Rundberg Community : mobile web application using Watson’s Translation, Speech-to-Text & Text-to-Speech
<strong>Technologies</strong>: android, javascript, java, xml, sqlite, mysql, Arduino C, node-red, Watson, html

•	Programmed applications using Java, Natclipse, Javascript, database , spring, struts, hibernate web application, and Job Control Language (JCL), performed unit testing.
•	Participated in Agile/Sprint Scrum meetings to customize and integrate Innowake tools into the client environment.
•	Developed, tested and debugged applications and dialogs refactored from Natural to Java: Adabas to db2, and Java Swing POS client to Java/Javascript client  in the back-end (mainly testing) and in the Swing/Web client (Spring Framework).
•	Project phases: Programmed and debugged backend Java application during 4-month  Pilot phase. Programmed and debugged frontend Java Swing application durig 4-month Iteration 1 Part 1 phase.
<strong>Technologies</strong>: xml, javascript, j2ee, swing, maven, CVS, JUnit, db2, SQL, Apache Tomcat, agile lifecycle, Jira

•	Contributed to the full software lifecycle, from defining requirements through successful deployment for different games with POS Altura, GT1100, GT1200 terminals and many other terminal types.
•	Analyzed user requirements, designed and programmed enhancements to core Java application in Embedded Software on lottery terminals accessed by millions of retailers worldwide.
•	Core Java programming, from AWT user interface coding for dialogs, multithreading, transaction, scripting (TML) to print, and back end performance design to communicate with attached platforms.
•	Used SSH from Windows to upload and debug code behavior (on logs) on terminals which runs on Linux operating system and its all attached hardware peripherals using Kshell.
•	Waterfall Software Design methodology, documentation & project code estimates.
•	Worked with projects teams in U.S. & abroad.
<strong>Technologies</strong>: java, xml, eclipse, linux, tml, CVS, SVN, waterfall lifecycle, Jira, Shell Scripting, Putty

•	Recognized the value and developed the algorithm to add a third vector for 2D Text Visualization graphic display. The third vector enablement of 3D Text Visualization to exponentially accelerate problem solving.
•	Data Mining (JSON, Carot2 Clustering Engine, Apache Lucene – Query Parser Syntax), Data Analysis and Preprocessing, Text index, k-means  and Visualization.
•	Algorithms (LDA) and Math Formulation.
•	Wrote and presented a paper on data visualization.
<strong>Technologies</strong>: machine learning, mathematical algorithms, eclipse, java, data analysis, lucene
